https://www.youtube.com/watch?v=OTPz5plKb40&list=PLZoTAELRMXVPwYGE2PXD3x0bfKnR0cJjN&index=2

https://www.youtube.com/watch?v=nmBqnKSSKfM&list=PLZoTAELRMXVPwYGE2PXD3x0bfKnR0cJjN&index=4

https://github.com/krishnaik06/Feature-Engineering-Live-sessions

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
cd /content/drive/MyDrive/DATASET-Aesthetix

/content/drive/MyDrive/DATASET-Aesthetix

In [ ]:
import pandas as pd

df=pd.read_csv('titanic.csv',usecols=['Sex'])

df.head(25)

       Sex
0     male
1   female
2   female
3   female
4     male
5     male
6     male
7     male
8   female
9   female
10  female
11  female
12    male
13    male
14  female
15  female
16    male
17    male
18  female
19  female
20    male
21    male
22  female
23    male
24  female

In [ ]:
pd.get_dummies(df)

     Sex_female  Sex_male
0             0         1
1             1         0
2             1         0
3             1         0
4             0         1
..          ...       ...
886           0         1
887           1         0
888           1         0
889           0         1
890           0         1

[891 rows x 2 columns]

In [ ]:
pd.get_dummies(df).head(3)

   Sex_female  Sex_male
0           0         1
1           1         0
2           1         0

In [ ]:
pd.get_dummies(df,drop_first=True).head()

   Sex_male
0         1
1         0
2         0
3         0
4         1

In [ ]:
df=pd.read_csv('titanic.csv',usecols=['Embarked'])
df.head()

  Embarked
0        S
1        C
2        S
3        S
4        S

In [ ]:
pd.get_dummies(df).head()

   Embarked_C  Embarked_Q  Embarked_S
0           0           0           1
1           1           0           0
2           0           0           1
3           0           0           1
4           0           0           1

In [ ]:
df['Embarked'].unique()

array(['S', 'C', 'Q', nan], dtype=object)

In [ ]:
df.dropna(inplace=True)

In [ ]:
df.head(10)

  Embarked
0        S
1        C
2        S
3        S
4        S
5        Q
6        S
7        S
8        S
9        C

In [ ]:
df['Embarked'].unique()

array(['S', 'C', 'Q'], dtype=object)

In [ ]:
pd.get_dummies(df).head()

   Embarked_C  Embarked_Q  Embarked_S
0           0           0           1
1           1           0           0
2           0           0           1
3           0           0           1
4           0           0           1

In [ ]:

pd.get_dummies(df,drop_first=True).head()

   Embarked_Q  Embarked_S
0           0           1
1           0           0
2           0           1
3           0           1
4           0           1

In [ ]:
#### Onehotencoding with many categories in a feature
df=pd.read_csv('mercedes.csv',usecols=["X0","X1","X2","X3","X4","X5","X6"])
df.head()

   X0 X1  X2 X3 X4 X5 X6
0   k  v  at  a  d  u  j
1   k  t  av  e  d  y  l
2  az  w   n  c  d  x  j
3  az  t   n  f  d  x  l
4  az  v   n  f  d  h  d

In [ ]:
for i in df.columns:
    print(len(df[i].unique()))

47
27
44
7
4
29
12

In [ ]:
df.X1.value_counts().sort_values(ascending=False).head(10)

aa    833
s     598
b     592
l     590
v     408
r     251
i     203
a     143
c     121
o      82
Name: X1, dtype: int64

In [ ]:
lst_10=df.X1.value_counts().sort_values(ascending=False).head(10).index
lst_10=list(lst_10)
lst_10

['aa', 's', 'b', 'l', 'v', 'r', 'i', 'a', 'c', 'o']

In [ ]:
import numpy as np
for categories in lst_10:
    df[categories]=np.where(df['X1']==categories,1,0)
lst_10.append('X1')
df[lst_10]

      aa  s  b  l  v  r  i  a  c  o X1
0      0  0  0  0  1  0  0  0  0  0  v
1      0  0  0  0  0  0  0  0  0  0  t
2      0  0  0  0  0  0  0  0  0  0  w
3      0  0  0  0  0  0  0  0  0  0  t
4      0  0  0  0  1  0  0  0  0  0  v
...   .. .. .. .. .. .. .. .. .. .. ..
4204   0  1  0  0  0  0  0  0  0  0  s
4205   0  0  0  0  0  0  0  0  0  1  o
4206   0  0  0  0  1  0  0  0  0  0  v
4207   0  0  0  0  0  1  0  0  0  0  r
4208   0  0  0  0  0  1  0  0  0  0  r

[4209 rows x 11 columns]

**Ordinal Number Encoding**

In [ ]:
import datetime
today_date=datetime.datetime.today()
today_date

datetime.datetime(2023, 11, 21, 10, 41, 21, 908701)

In [ ]:
today_date-datetime.timedelta(3)

datetime.datetime(2023, 11, 18, 10, 41, 21, 908701)

In [ ]:
#### List Comprehension
days=[today_date-datetime.timedelta(x) for x in range(0,15)]

In [ ]:
import pandas as pd
data=pd.DataFrame(days)
data.columns=["Day"]
data.head()

                         Day
0 2023-11-21 10:41:21.908701
1 2023-11-20 10:41:21.908701
2 2023-11-19 10:41:21.908701
3 2023-11-18 10:41:21.908701
4 2023-11-17 10:41:21.908701

In [ ]:
data['weekday']=data['Day'].dt.weekday
data.head()

                         Day  weekday
0 2023-11-21 10:41:21.908701        1
1 2023-11-20 10:41:21.908701        0
2 2023-11-19 10:41:21.908701        6
3 2023-11-18 10:41:21.908701        5
4 2023-11-17 10:41:21.908701        4

In [ ]:
dictionary={'Monday':1,'Tuesday':2,'Wednesday':3,'Thursday':4,'Friday':5,'Saturday':6,'Sunday':7}

In [ ]:
dictionary

{'Monday': 1,
 'Tuesday': 2,
 'Wednesday': 3,
 'Thursday': 4,
 'Friday': 5,
 'Saturday': 6,
 'Sunday': 7}

In [ ]:
data['weekday_ordinal']=data['weekday'].map(dictionary)
data

                          Day  weekday  weekday_ordinal
0  2023-11-21 10:41:21.908701        1              NaN
1  2023-11-20 10:41:21.908701        0              NaN
2  2023-11-19 10:41:21.908701        6              NaN
3  2023-11-18 10:41:21.908701        5              NaN
4  2023-11-17 10:41:21.908701        4              NaN
5  2023-11-16 10:41:21.908701        3              NaN
6  2023-11-15 10:41:21.908701        2              NaN
7  2023-11-14 10:41:21.908701        1              NaN
8  2023-11-13 10:41:21.908701        0              NaN
9  2023-11-12 10:41:21.908701        6              NaN
10 2023-11-11 10:41:21.908701        5              NaN
11 2023-11-10 10:41:21.908701        4              NaN
12 2023-11-09 10:41:21.908701        3              NaN
13 2023-11-08 10:41:21.908701        2              NaN
14 2023-11-07 10:41:21.908701        1              NaN

**Count Or Frequency Encoding**

In [ ]:
train_set = pd.read_csv('http://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.data' , header = None,index_col=None)
train_set.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

In [ ]:
columns=[1,3,5,6,7,8,9,13]
train_set=train_set[columns]
train_set.columns=['Employment','Degree','Status','Designation','family_job','Race','Sex','Country']
train_set.head()

,Employment,Degree,Status,Designation,family_job,Race,Sex,Country
0,State-gov,Bachelors,Never-married,Adm-clerical,Not-in-family,White,Male,United-States
1,Self-emp-not-inc,Bachelors,Married-civ-spouse,Exec-managerial,Husband,White,Male,United-States
2,Private,HS-grad,Divorced,Handlers-cleaners,Not-in-family,White,Male,United-States
3,Private,11th,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,United-States
4,Private,Bachelors,Married-civ-spouse,Prof-specialty,Wife,Black,Female,Cuba

In [ ]:
for feature in train_set.columns[:]:
    print(feature,":",len(train_set[feature].unique()),'labels')

Employment : 9 labels
Degree : 16 labels
Status : 7 labels
Designation : 15 labels
family_job : 6 labels
Race : 5 labels
Sex : 2 labels
Country : 42 labels

In [ ]:
country_map=train_set['Country'].value_counts().to_dict()
train_set['Country']=train_set['Country'].map(country_map)
train_set.head(20)

,Employment,Degree,Status,Designation,family_job,Race,Sex,Country
0,State-gov,Bachelors,Never-married,Adm-clerical,Not-in-family,White,Male,29170
1,Self-emp-not-inc,Bachelors,Married-civ-spouse,Exec-managerial,Husband,White,Male,29170
2,Private,HS-grad,Divorced,Handlers-cleaners,Not-in-family,White,Male,29170
3,Private,11th,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,29170
4,Private,Bachelors,Married-civ-spouse,Prof-specialty,Wife,Black,Female,95
5,Private,Masters,Married-civ-spouse,Exec-managerial,Wife,White,Female,29170
6,Private,9th,Married-spouse-absent,Other-service,Not-in-family,Black,Female,81
7,Self-emp-not-inc,HS-grad,Married-civ-spouse,Exec-managerial,Husband,White,Male,29170
8,Private,Masters,Never-married,Prof-specialty,Not-in-family,White,Female,29170
9,Private,Bachelors,Married-civ-spouse,Exec-managerial,Husband,White,Male,29170
10,Private,Some-college,Married-civ-spouse,Exec-managerial,Husband,Black,Male,29170
11,State-gov,Bachelors,Married-civ-spouse,Prof-specialty,Husband,Asian-Pac-Islander,Male,100
12,Private,Bachelors,Never-married,Adm-clerical,Own-child,White,Female,29170
13,Private,Assoc-acdm,Never-married,Sales,Not-in-family,Black,Male,29170
14,Private,Assoc-voc,Married-civ-spouse,Craft-repair,Husband,Asian-Pac-Islander,Male,583
15,Private,7th-8th,Married-civ-spouse,Transport-moving,Husband,Amer-Indian-Eskimo,Male,643
16,Self-emp-not-inc,HS-grad,Never-married,Farming-fishing,Own-child,White,Male,29170
17,Private,HS-grad,Never-married,Machine-op-inspct,Unmarried,White,Male,29170
18,Private,11th,Married-civ-spouse,Sales,Husband,White,Male,29170
19,Self-emp-not-inc,Masters,Divorced,Exec-managerial,Unmarried,White,Female,29170

**Advantages**

Easy To Use

Not increasing feature space

**Disadvantages**

It will provide same weight if the frequencies are same

**Target Guided Ordinal Encoding**

Ordering the labels according to the target

Replace the labels by the joint probability of being 1 or 0

In [ ]:
import pandas as pd
df=pd.read_csv('titanic.csv', usecols=['Cabin','Survived'])
df.head()

   Survived Cabin
0         0   NaN
1         1   C85
2         1   NaN
3         1  C123
4         0   NaN

In [ ]:
df['Cabin'].fillna('Missing',inplace=True)
df['Cabin']=df['Cabin'].astype(str).str[0]
df.head()

   Survived Cabin
0         0     M
1         1     C
2         1     M
3         1     C
4         0     M

In [ ]:
df.Cabin.unique()

array(['M', 'C', 'E', 'G', 'D', 'A', 'B', 'F', 'T'], dtype=object)

In [ ]:
df.groupby(['Cabin'])['Survived'].mean()

Cabin
A    0.466667
B    0.744681
C    0.593220
D    0.757576
E    0.750000
F    0.615385
G    0.500000
M    0.299854
T    0.000000
Name: Survived, dtype: float64

In [ ]:
df.groupby(['Cabin'])['Survived'].mean().sort_values().index

Index(['T', 'M', 'A', 'G', 'C', 'F', 'B', 'E', 'D'], dtype='object', name='Cabin')

In [ ]:
ordinal_labels=df.groupby(['Cabin'])['Survived'].mean().sort_values().index
ordinal_labels

Index(['T', 'M', 'A', 'G', 'C', 'F', 'B', 'E', 'D'], dtype='object', name='Cabin')

In [ ]:
enumerate(ordinal_labels,0)

In [ ]:
ordinal_labels2={k:i for i,k in enumerate(ordinal_labels,0)}
ordinal_labels2

{'T': 0, 'M': 1, 'A': 2, 'G': 3, 'C': 4, 'F': 5, 'B': 6, 'E': 7, 'D': 8}

In [ ]:
df['Cabin_ordinal_labels']=df['Cabin'].map(ordinal_labels2)
df.head()

   Survived Cabin  Cabin_ordinal_labels
0         0     M                     1
1         1     C                     4
2         1     M                     1
3         1     C                     4
4         0     M                     1

**Mean Encoding**

In [ ]:
mean_ordinal=df.groupby(['Cabin'])['Survived'].mean().to_dict()
mean_ordinal

{'A': 0.4666666666666667,
 'B': 0.7446808510638298,
 'C': 0.5932203389830508,
 'D': 0.7575757575757576,
 'E': 0.75,
 'F': 0.6153846153846154,
 'G': 0.5,
 'M': 0.29985443959243085,
 'T': 0.0}

In [ ]:
df['mean_ordinal_encode']=df['Cabin'].map(mean_ordinal)
df.head()

   Survived Cabin  Cabin_ordinal_labels  mean_ordinal_encode
0         0     M                     1             0.299854
1         1     C                     4             0.593220
2         1     M                     1             0.299854
3         1     C                     4             0.593220
4         0     M                     1             0.299854